### ISSUE TITLE
Asset structure in Blender 4.1

### ISSUE THREAD

**Issue by tsykhra** [Poly-Haven/polyhavenassets#101]
I've installed and fetched all assets in Blender 4.0.
It installed correctly and showing all categories, but in 4.1 Beta there are no categories. 

<img width="781" alt="Screenshot 2024-02-15 at 02 01 25" src="https://github.com/Poly-Haven/polyhavenassets/assets/113416361/d1976a54-082c-408f-97fd-d3282b834b3b">

Sonoma 14.3, M3 Max

**Comment by gregzaal** [comment]
Please check our docs and troubleshooting guide :) https://docs.polyhaven.com/en/guides/blender-addon#troubleshooting
This typically just requires a restart of Blender.

**Comment by tsykhra** [comment]
Restart, reboot, revalidation - no luck

**Comment by gregzaal** [comment]
@tsykhra Hmm, sorry about that. Can you please fill out our bug report template so I can have some more information to help you?

----

**Describe the bug**
A clear and concise description of what the bug is.

**Console log**
Start blender from a command prompt/terminal (https://docs.blender.org/manual/en/latest/advanced/command_line/launch/index.html), reproduce the issue and paste the entire console output here:

```
PASTE CONSOLE OUTPUT HERE
```

**To Reproduce**
Steps to reproduce the behavior, starting from an empty scene in Blender:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by tsykhra** [comment]
It's a miracle! Today I booted up and everything showed up! Thanks!

**Comment by tsykhra** [comment]
Closing

**Comment by gregzaal** [comment]
Glad to hear it :)
