### ISSUE TITLE
Drag & Drop not working on 3.6

### ISSUE THREAD

**Issue by scstudio** [Poly-Haven/polyhavenassets#103]
I'm not able to drag and drop items using Blender 3.6
My Library is located in d:\Blender Assets\Poly Haven
All of the assets show in library but none will drag and drop
The plug in is version 1.1.6
Thanks
SCS

**Comment by gregzaal** [comment]
Hey there,

If the assets show up in the browser, but then can't be dragged and dropped, then it's likely not a problem with our add-on but something in Blender itself causing the problem. Sometimes this can be related to using multiple Blender versions.

I would suggest installing the latest version of Blender (4.0), [Revalidating](https://docs.polyhaven.com/images/2023-08-22_08-21-08.png) your assets and trying again. If that does not help, then try completely deleting your asset library and fetching it again.

Finally, if you're still unable to resolve it yourself, please submit a [new bug report using the template](https://github.com/Poly-Haven/polyhavenassets/issues/new?assignees=&labels=&template=bug_report.md&title=) provided so that I have enough information to investigate the problem.
