### ISSUE TITLE
No Prefetch assets button in later launched of Blender

### ISSUE THREAD

**Issue by kesitrifork** [Poly-Haven/polyhavenassets#109]
Hi PolyHaven

I have a standard installation of Blender 4.1

I followed the video and installed Polyhaven, it worked great and I have both HDRI and textures.

However now I want models and the button is not there. I have tried to install the plugin again but it does not appear.

It is the only plugin I have installed as it is my first plugin experience.

I am not sure how to debug it further. Enabling and disabling the plugin does nothing unfortunate.

**Comment by gregzaal** [comment]
Hi there, have you got the Poly Haven library selected from the dropdown? If so and there's still a problem, first check [our troubleshooting guide on this topic](https://docs.polyhaven.com/en/guides/blender-addon#there-is-no-fetch-assets-button), and if that still doesn't help, please make a complete bug report using the provided template so that I have more information to help you.
