### ISSUE TITLE
Fix texture scale has a bug

### ISSUE THREAD

**Issue by kesitrifork** [Poly-Haven/polyhavenassets#110]
Here I made a new blender file

Made a plane, change the default light to a sun, placed a asset on the plane and it looks by default like this

<img width="1840" alt="image" src="https://github.com/Poly-Haven/polyhavenassets/assets/152864720/c04973c3-e81b-4b22-a36c-8a583f072410">

<img width="1840" alt="image" src="https://github.com/Poly-Haven/polyhavenassets/assets/152864720/f980d09b-29f3-4d62-a048-faffc2604a06">

Clicking the Fix Texture scale makes it look like this

<img width="1840" alt="image" src="https://github.com/Poly-Haven/polyhavenassets/assets/152864720/49deed66-5ffe-4286-8ffa-49d1f72162ae">

<img width="1840" alt="image" src="https://github.com/Poly-Haven/polyhavenassets/assets/152864720/1e504994-3511-4c15-989c-3c92d7dd6590">

It looks like there is a bug where it puts it to 0.0025 in all cases which is wrong

<img width="396" alt="image" src="https://github.com/Poly-Haven/polyhavenassets/assets/152864720/29cad8ce-2e87-45dd-83a7-4cf687864648">

**Comment by gregzaal** [comment]
Hey there,

The "Fix texture scale" function works on my side. The texture you have selected is an aerial scan, 80 meters wide. Also note that the scale must be applied on your plane to work correctly. If you still experience consistent problems, please make a full but report using the provided template so that I can assist further.
