### ISSUE TITLE
No polyhavenasset.x.x.x folder in addons (MAC)

### ISSUE THREAD

**Issue by jpwill20** [Poly-Haven/polyhavenassets#24]
It seems when I go into my user library application support folder, there is no polyhavenassets.x.x.x
Strangely, I have the polyhavenassets-main though.  I tried renaming the main folder to just polyhavenassets and creating a new folder called polyhavenassets, but it seems nothing is working. 
Even if I remove the add-on and install an older version IE 1.0.6, no polyhavenassets-1.0.6 folder appears.

I am VERY confused.

**Comment by gregzaal** [comment]
Hi, simply installing the ZIP you downloaded (whether `-main` branch or the latest version release `-1.0.6` doesn't matter currently, since they are the same) and then renaming the installed folder from `polyhavenassets-[whatever]` to `polyhavenassets` should work and has been tested on Mac.

Generally we only have the resources to provide user support to paying customers, so further than this I'm afraid I can't help you figure things out further.
