### ISSUE TITLE
so im having a eror wen im  trying to fetch assets

### ISSUE THREAD

**Issue by polybobz** [Poly-Haven/polyhavenassets#32]
![Screenshot (89)](https://user-images.githubusercontent.com/106483693/202423500-a0417d76-513e-4c0d-bb8e-dfd682402b18.png)
![Screenshot (90)](https://user-images.githubusercontent.com/106483693/202423510-5495dd00-a2dc-44d9-b0b9-b361914c9c2b.png)
![among-us-sus](https://user-images.githubusercontent.com/106483693/202423556-3837375c-8635-46b3-8ca0-c0a32eed21e6.gif)
[log.txt](https://github.com/Poly-Haven/polyhavenassets/files/10030547/log.txt)
log.txt have the log in it

**Comment by gregzaal** [comment]
Hi, as mentioned on Discord, I'll need more information to help diagnose this problem. Based on the info above it doesn't make any sense and should not be happening.

Your `log.txt` is only a partial log which doesn't give any more info than the screenshots. I'll need a full clean log from launching Blender from a command prompt, with factory defaults.

As mentioned on Discord, I also need exact list of steps to reproduce the problem, starting from factory defaults. Weird issues like this are often caused by conflicts with other add-ons, so that will help diagnose it too.
