### ISSUE TITLE
Assets Liberary Cant't Access

### ISSUE THREAD

**Issue by Yvivekguru** [Poly-Haven/polyhavenassets#41]
When I make Assets Library this not able to fetch the poly heven assets

**Comment by gregzaal** [comment]
Hi there,

There is not sufficient information in this report for us to understand the issue or do anything about.

Please check our [troubleshooting guide](https://github.com/Poly-Haven/polyhavenassets/wiki/Troubleshooting) for common problems. If your issue is not present there, please submit a [full bug report](https://github.com/Poly-Haven/polyhavenassets/issues/new?assignees=&labels=&template=bug_report.md&title=) using the template provided.
