### ISSUE TITLE
"Fetch assets" button doesn't show

### ISSUE THREAD

**Issue by SmartPadawan** [Poly-Haven/polyhavenassets#67]
**Describe the bug**
"Fetch assets" button doesn't show

**Console log**
Start blender from a command prompt/terminal (https://docs.blender.org/manual/en/latest/advanced/command_line/launch/index.html), reproduce the issue and paste the entire console output here:

```
Read prefs: C:\Users\cesco\AppData\Roaming\Blender Foundation\Blender\3.5\config\userpref.blend
SIMPLEBAKE: There is a newer version of SimpleBake available
HardOps 0.9.87.35 available!
C:\Users\cesco\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\auto_eye_v03_4_addon\auto_eye.blend
chocofur_model_manager_28 addon: Verbose is enabled
chocofur_model_manager_28 addon: Read in JSON settings from file
RetopoFlow: Initial load
WARN (bgl): C:\Users\blender\git\blender-v350\blender.git\source\blender\python\generic\bgl.c:54 report_deprecated_call: 'bgl.glGetString' is deprecated and will be removed in Blender 4.0. Report or update your script to use 'gpu' module.
Addon Common: (shaders) GLSL Version: 4.50 NVIDIA
WARN (bgl): C:\Users\blender\git\blender-v350\blender.git\source\blender\python\generic\bgl.c:54 report_deprecated_call: 'bgl.glGetError' is deprecated and will be removed in Blender 4.0. Report or update your script to use 'gpu' module.
WARN (bgl): C:\Users\blender\git\blender-v350\blender.git\source\blender\python\generic\bgl.c:54 report_deprecated_call: 'bgl.glGetError' is deprecated and will be removed in Blender 4.0. Report or update your script to use 'gpu' module.
WARN (bgl): C:\Users\blender\git\blender-v350\blender.git\source\blender\python\generic\bgl.c:54 report_deprecated_call: 'bgl.glGetError' is deprecated and will be removed in Blender 4.0. Report or update your script to use 'gpu' module.
WARN (bgl): C:\Users\blender\git\blender-v350\blender.git\source\blender\python\generic\bgl.c:54 report_deprecated_call: 'bgl.glGetError' is deprecated and will be removed in Blender 4.0. Report or update your script to use 'gpu' module.
WARN (bgl): C:\Users\blender\git\blender-v350\blender.git\source\blender\python\generic\bgl.c:54 report_deprecated_call: 'bgl.glGetError' is deprecated and will be removed in Blender 4.0. Report or update your script to use 'gpu' module.
WARN (bgl): C:\Users\blender\git\blender-v350\blender.git\source\blender\python\generic\bgl.c:54 report_deprecated_call: 'bgl.glGetError' is deprecated and will be removed in Blender 4.0. Report or update your script to use 'gpu' module.
WARN (bgl): C:\Users\blender\git\blender-v350\blender.git\source\blender\python\generic\bgl.c:54 report_deprecated_call: 'bgl.glGetError' is deprecated and will be removed in Blender 4.0. Report or update your script to use 'gpu' module.
WARN (bgl): C:\Users\blender\git\blender-v350\blender.git\source\blender\python\generic\bgl.c:54 report_deprecated_call: 'bgl.glGetError' is deprecated and will be removed in Blender 4.0. Report or update your script to use 'gpu' module.
WARN (bgl): C:\Users\blender\git\blender-v350\blender.git\source\blender\python\generic\bgl.c:54 report_deprecated_call: 'bgl.glGetError' is deprecated and will be removed in Blender 4.0. Report or update your script to use 'gpu' module.
Addon Common: compiling UI shader
Addon Common: batching for shader
Addon Common: UI shader initialized
Addon Common: ########################################
              Loading shader using Shader
RetopoFlow Shader Info: uiShader (28)
  attribs:
  uniforms: uMVPMatrix (23), left (12), right (21), top (22), bottom (7), width (25), height (9), depth (8), margin_left (14), margin_right (15), margin_top (16), margin_bottom (13), padding_left (18), padding_right (19), padding_top (20), padding_bottom (17), border_width (6), border_radius (3), border_left_color (2), border_right_color (4), border_top_color (5), border_bottom_color (1), background_color (0), using_image (24), image_fit (11), image (10)
RetopoFlow git: None
gpustate.gpu_info cannot get shader version!
RetopoFlow options path: C:\Users\cesco\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\RetopoFlow\RetopoFlow_options.json
Addon Common: (bmesh_render) GLSL Version: NVIDIA Corporation, NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2, 4.5.0 NVIDIA 531.61, (no shader version)
cgcookie addon: Verbose is enabled
cgcookie addon: Read in JSON settings from file
register_class(...):
Warning: 'MATERIAL_MT_category_Stucco_&_Stuff' doesn't have an alpha-numeric suffix
```

**Additional context**
I tried to deactivate every other addon that could in some way change the UI. it doesn't work.
Tried to uninstall it and reinstall with blender windows app, .exe  and .zip
created file path for the assets on other drives...
nothing seems to work

thanks

**Comment by gregzaal** [comment]
Hi Francesco,

Unfortunately this information doesn't indicate any issue with our add-on, all the errors and warnings in your console log are from other add-ons.

So far every report I've received with the same problem has always been caused by another add-on overriding our UI. I know you've tried to narrow down that problem, but I can see in your console log there are still many add-ons enabled, so we'll need to dig deeper.

Please try to reproduce the issue from Blender's **factory defaults** so that I might be able to do the same and see what's wrong. To do this:

0. Optionally back up your user preferences folder (`C:\Users\cesco\AppData\Roaming\Blender Foundation\Blender\3.5`) so that you can revert back to them later.
1. Open Blender and go to File > Defaults > Load Factory Settings.
2. Open the Preferences and make sure to manually save them.
3. Restart Blender - this is important in case other add-ons don't uninstall themselves correctly.
4. Open the system console like you did before - it's critical to do this before you install the add-on.
5. Install our add-on.
6. Set your Poly Haven asset library path as before. Double check the add-on is detecting the library path correctly and not giving a warning.
7. Close the preferences window and open an Asset Browser editor.
8. Select the Poly Haven library.
9. If the button is now present, this means one of your other add-ons is causing the problem, and you will need to manually narrow down which one and contact the author to ask them to fix it.
10. If the button is still missing, move the mouse around the header of the Asset Browser where the button should be appearing (this triggers Blender to update the UI where the mouse is, and should spam any errors).
11. Take a screenshot of the full Blender window and share it here.
12. Paste the **entire** output of the console here. If there's a problem with our add-on, some evidence is sure to be mentioned somewhere there.
13. For good measure, please also go to Help > Save System Info and upload/paste the file here.

**Comment by SmartPadawan** [comment]
Restoring factory settings worked. 
i figured out that the problem was caused by startup file. I heavily changed it. Restoring userpref.blend keeps the button visible. restoring startupfile doesn't. 
i created the startup file in a past version of blender. that can be the problem? there's a setting in it that keeps hiding the "fetch assets" button, i couldn't find it for now. 
Anyway, thanks for the help. i preferred to keep my startup preferences, but it's part of blender experience i guess :)

**Comment by gregzaal** [comment]
That's interesting, glad you got it sorted then :) I'll keep that in mind for anyone else who has similar issues.
