### ISSUE TITLE
Cannot change HDRI resolution

### ISSUE THREAD

**Issue by maard** [Poly-Haven/polyhavenassets#78]
Hi. Can be related to #64

**Describe the bug**

Bender 3.6, addon 1.1.3.
Asset browser set to "Append (Reuse data)".

*World material setup:*
![image](https://github.com/Poly-Haven/polyhavenassets/assets/107768/48aa4796-91cb-4557-a75b-8476c9af91f1)

*Missing drop down*
![image](https://github.com/Poly-Haven/polyhavenassets/assets/107768/1c921be4-5cf2-4515-8d0c-200224d99bab)

**Expected behavior**

Described in addon documentation: [world settings](https://user-images.githubusercontent.com/5604661/187624587-ea7ee0be-6805-46f4-ad8e-97a9c8e679e1.png)

**Additional info**

Happens with HDRI only. For textures the "1k" drop down appears as expected, and i can download higher res textures.

![image](https://github.com/Poly-Haven/polyhavenassets/assets/107768/fc7c9657-9e5c-4b0b-9e75-31ada687d2f9)

**Comment by gregzaal** [comment]
Hi there,

Without filling in the complete bug report template, I'm unable to help you much with this, as it's working fine for me.

I would guess that there is an issue with the file paths in your library, which might be solved by deleting your asset folder and redownloading them.

If that doesn't help, please complete the full bug report template so that I can assist further.
