### ISSUE TITLE
Poly Haven addon - assets not downloading / UI not visible

### ISSUE THREAD

**Issue by grootlicht** [Poly-Haven/polyhavenassets#91]
Hi,

Yesterday I purchased the Poly Haven addon for Blender, the $30,- variant. I installed and enabled the addon in Blender 3.6 (Windows 10), created a new library folder 'Poly Haven' and tried to download the assets. In the folder there's a .txt file; blender_assets.cats.txt with all URL's, but there are no assets downloaded after several hours. 

Also there are no Poly Haven UI elements in the Asset Browser visible. 

I've searched for tutorials an forum posts about this problem, but couldn't find any. I installed the addon several times, restarted Blender etc, nothing seems to work. What's going wrong here? 

Hope you can help,
Ivo

![PolyHaven-Bug-01](https://github.com/Poly-Haven/polyhavenassets/assets/2239712/35d0bffb-9fbc-4f22-a2cf-f311763e8dc1)

**Comment by gregzaal** [comment]
Hi there,

The first step is to check through our troubleshooting guide and see if you're not having one of the issues there. If not, please create a complete bug report [using the template](https://github.com/Poly-Haven/polyhavenassets/issues/new?assignees=&labels=&template=bug_report.md&title=) provided so that I can help debug the problem.
